runtime: python311
entrypoint: gunicorn -b :$PORT main:app --workers 2 --threads 8 --timeout 0
instance_class: F2
automatic_scaling:
  max_instances: 3
  min_instances: 0
  target_cpu_utilization: 0.6
  max_concurrent_requests: 80
