runtime: nodejs20
instance_class: F2

# Astro SSR environment variables
env_variables:
  # The host expected by Astro node adapter
  HOST: '0.0.0.0'
  # Node environment
  NODE_ENV: 'production'

handlers:
  # 1. Astro built assets (hashed) - Long Cache (1 year)
  # served from dist/client/_astro
  - url: /_astro
    static_dir: dist/client/_astro
    expiration: 365d
    secure: always

  # 2. Main Index Page - NO CACHE
  # ensures users always get the latest version pointing to new CSS/JS
  - url: /
    static_files: dist/client/index.html
    upload: dist/client/index.html
    expiration: 0s
    secure: always

  # 3. Root static files (robots.txt, favicon.ico, sitemap) - Moderate Cache (1 day)
  - url: /(robots\.txt|favicon\.ico|sitemap.*\.xml)$
    static_files: dist/client/\1
    upload: dist/client/(robots\.txt|favicon\.ico|sitemap.*\.xml)$
    expiration: 1d
    secure: always

  # 4. Catch-all to Node.js app
  # Handles all other routes (dynamic pages, API, sub-pages)
  - url: .*
    script: auto
    secure: always
